config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index" 
  resources :posts do
    resources :replies
    collection do
      get :feeds
    end

    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: :show
  resources :users, only: [:show, :edit, :update] do
    member do
      get :my_comment
      get :my_collect
      get :my_draft
      get :my_friend
    end
  end

  resources :friendships, only: [:create, :destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :replies, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_posts, through: :collects, source: :post

  has_many :friendships, dependent: :destroy #, class_name: "friendship", primary_key: "id", foreign_key: "user_id"
  has_many :friends, through: :friendships #, source: :friend

  has_many :inverse_friends, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friendlys, through: :inverse_friends, source: :user

  mount_uploader :avatar, AvatarUploader

  before_create :generate_authentication_token

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

  def admin?
    self.role == "admin"
  end

  def friend?(user)
    self.friends.include?(user)
  end

  def friendly?(user)
    self.friendlys.include?(user)
  end

  def all_friends
    friends = (self.friends + self.friendlys).uniq
  end

  def friended
    friends = (self.friends + self.friendlys)

    friended = friends.select{|item| friends.count(item) > 1}.uniq
  end


  def friend_waiting
    friend_waiting = self.friends - self.friended    
  end

  def friendly_to_accept
    friendly_to_accept = self.friendlys - self.friended
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users=User.page(params[:page]).per(10)  
  end

  def update
    set_user
    if @user.update(user_params)
      redirect_to admin_users_path
      flash[:notice] = "user was successfully updated"
    else
      @users = User.page(params[:page]).per(10)  
      render :index
    end    
  end

  private

  def user_params
    params.require(:user).permit(:role)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
 
  def show
    @posts = @user.posts.readable_by(current_user).where(status: "Published")
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def my_comment
    
  end

  def my_collect
    @posts = @user.collected_posts.readable_by(current_user)

  end

  def my_draft
    @posts = @user.posts.where(status: "Draft")
     
  end

  def my_friend
    
  end

  private

  def set_user
     @user = User.find(params[:id])
   end

  def user_params
    params.require(:user).permit(:name, :introduction, :avatar)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "自我介紹" %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar, "大頭照上傳" %>
          <%= image_tag @user.avatar if @user.avatar? %>
          <%= f.file_field :avatar %>
        </div>
        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/my_collect.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_top" %>
    <div class="clearfix"></div>

    <div class="col-xs-10 col-xs-offset-1">
      <ul class="nav nav-tabs">
        <li role="presentation" class="nav-link">
          <%= link_to 'My Post', user_path(@user) %> 
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Comment', my_comment_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link active">
          <%= link_to 'My Collect', my_collect_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Draft', my_draft_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Friend', my_friend_user_path(@user) %>
        </li>
      </ul>
  <br />

      <% @posts.each do |post| %>
        <%= post.title %>
        <div id="collect-btn">
          <%= render partial: "shared/collect_btn", :locals => { :@post => post } %>
        </div>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/my_comment.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_top" %>
    <div class="clearfix"></div>

    <div class="col-xs-10 col-xs-offset-1">
      <ul class="nav nav-tabs">
        <li role="presentation" class="nav-link">
          <%= link_to 'My Post', user_path(@user) %> 
        </li>

        <li role="presentation" class="nav-link active">
          <%= link_to 'My Comment', my_comment_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Collect', my_collect_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Draft', my_draft_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Friend', my_friend_user_path(@user) %>
        </li>
      </ul>
  <br />


      <% @user.replies.each do |reply| %>
        <% if reply.post.readable_by(current_user) %>
          <h4><%= link_to reply.post.title, post_path(reply.post) %></h4>
          <div class="form-group col-xs-8">
            <textarea class="form-control" rows="3" > <%= reply.comment %> </textarea>
          </div>
          <div class="col-xs-4">
            <%= link_to 'Edit', edit_post_reply_path(reply.post, reply) %>
            <%= link_to 'Delete', post_reply_path(reply.post, reply), method: :delete, data: {confirm:"Are you sure?"} %>
          </div>
        <div class="clearfix"></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/my_draft.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_top" %>
    <div class="clearfix"></div>

    <div class="col-xs-10 col-xs-offset-1">
      <ul class="nav nav-tabs">
        <li role="presentation" class="nav-link">
          <%= link_to 'My Post', user_path(@user) %> 
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Comment', my_comment_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Collect', my_collect_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link active">
          <%= link_to 'My Draft', my_draft_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Friend', my_friend_user_path(@user) %>
        </li>
      </ul>
  <br />
      <% if @user == current_user %>
        <%= render partial: "shared/user_posts" %>
      <% else %>
        <p>You are not allowed to see other's drafts</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/my_friend.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_top" %>
    <div class="clearfix"></div>

    <div class="col-xs-10 col-xs-offset-1">
      <ul class="nav nav-tabs">
        <li role="presentation" class="nav-link">
          <%= link_to 'My Post', user_path(@user) %> 
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Comment', my_comment_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Collect', my_collect_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Draft', my_draft_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link active">
          <%= link_to 'My Friend', my_friend_user_path(@user) %>
        </li>
      </ul>
  <br />


      <h3>Waiting for response </h3>
      
      <% @user.friend_waiting.each do |user| %>
        <div class="col-xs-4 col-sm-3">
          <%= image_tag user.avatar, class: "img-responsive img-rounded"%>
          <%= link_to user.name, user_path(user) %> 
          <div class="clearfix"></div>
        </div>
      <% end %>
      <div class="clearfix"></div>
  <hr />
      <h3>Friends to be accepted</h3>
      <% @user.friendly_to_accept.each do |user| %>
        <div class="col-xs-4 col-sm-3">
          <%= image_tag user.avatar, class: "img-responsive img-rounded" %>
          <%= link_to user.name, user_path(user) %>
          <div id="post_friend">
            <%= render partial: "shared/friend", locals: {user: user} %>          
          </div> 
        </div>
      <% end %>
      <div class="clearfix"></div>
  <hr />
      <h3>Confirmed friends</h3>
      <% @user.friended.each do |user| %>
        <div class="col-xs-4 col-sm-3">
          <%= image_tag user.avatar, class: "img-responsive img-rounded" %>
          <%= link_to user.name, user_path(user) %> 
        </div>
      <% end %>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_top" %>
    <div class="clearfix"></div>

    <div class="col-xs-10 col-xs-offset-1">
      <ul class="nav nav-tabs">
        <li role="presentation" class="nav-link active">
          <%= link_to 'My Post', user_path(@user) %> 
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Comment', my_comment_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Collect', my_collect_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Draft', my_draft_user_path(@user) %>
        </li>

        <li role="presentation" class="nav-link">
          <%= link_to 'My Friend', my_friend_user_path(@user) %>
        </li>
      </ul>
  <br />

      <%= render partial: "shared/user_posts" %>
    </div>
  </div>
</div>