config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index" 
  resources :posts do
    resources :replies
    collection do
      get :feeds
    end

    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: :show
  resources :users, only: [:show, :edit, :update] do
    member do
      get :my_comment
      get :my_collect
      get :my_draft
      get :my_friend
    end
  end

  resources :friendships, only: [:create, :destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users
  end
end

app/views/shared/_collect_btn.html.erb
    <% if @post.is_collected?(current_user) %>
      <%= link_to 'Uncollect', uncollect_post_path(@post), remote: true,method: :post, class: "btn btn-info" %>
    <% else %>
      <%= link_to 'Collect', collect_post_path(@post), remote: true, method: :post, class: "btn btn-primary" %>
    <% end %>

app/views/shared/_form_post.html.erb
<div class="container">
  <div class="row">

    <% if @post.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>
    
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      </div>

      <div class="form-group">
        <%= f.text_area :description, class: "form-control", placeholder: "" %>
      </div>

      <div class="form-group">
        <%= image_tag @post.image, width: '300px' if @post.image? %>
        <%= f.file_field :image, class: "form-control-file" %>
      </div>

      <h4> Category </h4>  
      <%= f.collection_check_boxes :category_id, Category.all, :id, :name do |category| %>
        <label class="checkbox-inline">
          <%= category.check_box %>
          <%= category.label %>
        </label>
      <% end %>
      
      <h4> Who Can See </h4>
      <%= f.collection_radio_buttons :authorized, [["all", " all "] ,["friends", " friends "], ["self", " self "]], :first, :last %> 

      <h4> Status: </h4>

      <div class="form-group">
        <!-- Save draft btn -->
      </div>

      <div class="form-group">
        <%= f.submit "Save as Draft", class: "btn btn-default" %>
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_friend.html.erb
<% if current_user != user %>
  <% if current_user.friend?(user) %>
    <%= link_to "Unfriend", friendship_path(user), remote: true, method: :delete, class: "btn btn-default" %>
  <% else %>
    <%= link_to "Friend", friendships_path(friend_id: user.id), remote: true, method: :post, class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/shared/_post_list.html.erb
    <div class="col-md-12">


      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th class="text-center col-md-2">
              <%= sort_link(@q, :replies_count, "Replies count", default_order: :desc) %>
            </th>
            <th class="col-md-6">
              <%= sort_link(@q, :title, "Title", default_order: :desc) %>
            </th>
            <th class="text-center col-md-2">
              <%= sort_link(@q, :last_replied_at, "Last replied at", default_order: :desc) %>
            </th>
            <th class="text-center col-md-2">
              <%= sort_link(@q, :views_count, "Viewed count", default_order: :desc) %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <th scope="row" class="text-center"><%= post.replies_count %></th>
            <td><%= link_to post.title, post_path(post) %></td>
            <td class="text-center"> 
              <% if post.replies.present? %>
                <%= (post.replies.last.created_at).strftime("%Y-%m-%d") %>
              <% end %>
            </td>
            <td class="text-center">
              <%= post.views_count %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @posts %>
      </div>

    </div>

app/views/shared/_user_posts.html.erb
      <table class="table table-striped table-bordered">
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, post_path(post) %></td>
            <td>
              <%= post.status %>
            </td>
            <td>
              <%= (post.created_at).strftime("%Y-%m-%d") %>
            </td>
            <td>
              <%= link_to 'Edit', edit_post_path(post) %>
              <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm:"Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New post', new_post_path, class: "btn btn-primary" %>

app/views/shared/_user_top.html.erb
<div class="col-md-10 col-md-offset-1">

  <!-- page-header 裡面顯示個人檔案資料 -->
  <div class="page-header">

    <div class="col-xs-3 col-md-3 col-sm-4">
      <div class="text-center">
        <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
      </div>
    </div>

    <div class="col-md-9 col-sm-8">
      <h2><%= @user.name %></h2>
      <p><strong><%= @user.email %></strong></p>
      <div><%= simple_format @user.introduction %></div>
      <% if @user.email == current_user.email %>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
      <% else %>
        <%= render partial: "shared/friend", locals: {user: @user} %>
      <% end %>
    </div>
    <div class="clearfix"></div>

  </div>

  <br>



</div>