config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index" 
  resources :posts do
    resources :replies
    collection do
      get :feeds
    end

    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: :show
  resources :users, only: [:show, :edit, :update] do
    member do
      get :my_comment
      get :my_collect
      get :my_draft
      get :my_friend
    end
  end

  resources :friendships, only: [:create, :destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  has_many :replies, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user

  mount_uploader :image, PhotoUploader

  validates_presence_of :title, :authorized

    
  def is_collected?(user)
    self.collected_users.include?(user)
  end

  def self.readable_by(user)
    Post.where(authorized: "friends", user: user.all_friends).or(Post.where(authorized: "all")).or(Post.where(user: user))  
  end

  def readable_by(user)
    Post.readable_by(user).include?(self)
  end

  def count_view
    self.views_count += 1
    self.save
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  
  def index
    @posts = Post.page(params[:page]).per(10)
  end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  before_action :authenticate_user!, except: :index

  def index
    if current_user
      @posts = Post.readable_by(current_user).where(status: "Published")
    else
      @posts = Post.where(authorized: "all", status: "Published")
    end
  end

  def show
  @post = Post.readable_by(current_user).where(status: "Published").find_by(id: params[:id])
    if !@post
      render json: {
        message: "Can't find the post!",
        status: 400
      }
    else
      render "api/v1/posts/show"
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render json: {
        message: "Post created successfully!",
        result: @post
      }
    else
      render json: {
        errors: @post.errors
      }
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      render json: {
        message: "Post updated successfully!",
        result: @post
      }
    else
      render json: {
        errors: @post.errors
      }
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    render json: {
      message: "Post destroy successfully!"
    }
  end

  private

  def post_params
    params.permit(:title, :description, :user, :authorized)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
      posts = Post.readable_by(current_user).where(status: "Published")
    else
      posts = Post.where(authorized: "all", status: "Published")
    end
    # posts = Post.readable_by(current_user).where(status: "Published")
    @q = posts.ransack(params[:q])

    @posts = @q.result.order(id: :asc).page(params[:page]).per(20)

    # @posts = Post.readable_by(current_user).order(created_at: :desc).page(params[:page]).per(20)
    @categories = Category.all
  end

  def show
    if @post.readable_by(current_user) && @post.status == "Published"
      @replies = @post.replies.page(params[:page]).per(20)
      if params[:reply_id]
        @reply = Reply.find(params[:reply_id])
      else
        @reply = Reply.new
      end
    else
      redirect_to posts_path
      flash[:alert] = "you are not authorized to see that post"
    end
    # @post.views_count += 1
    @post.count_view
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save      
      if published?
        flash[:notice] = "post was successfully created"
        @post.status = "Published"
        @post.save
        redirect_to posts_path
      elsif draft?
        flash[:notice] = "post was save as draft"
        @post.status = "Draft"
        @post.save
        redirect_to my_draft_user_path(current_user)
      end      
    else
      flash.now[:alert] = "post was failed to create"
      render :new
    end
  end

  def edit
    if @post.user == current_user
      @categories = Category.all
    else
      redirect_to posts_path
      flash[:alert] = "you are not allowed to edit other's post"
    end
  end

  def update
    @post.user = current_user
    if @post.update_attributes(post_params)    
      if published?
        flash[:notice] = "post was successfully updated"
        @post.status = "Published"
        @post.update_attributes(post_params)
        redirect_to posts_path
      elsif draft?
        flash[:notice] = "post was save as draft"
        @post.status = "Draft"
        @post.update_attributes(post_params)
        redirect_to my_draft_user_path(current_user)
      end
      
    else
      flash.now[:alert] = "post was failed to update"
      render :edit
    end   
  end

  def destroy
    @post.destroy
    redirect_to root_path
    flash[:alert] = "post was deleted"
  end

  def feeds
    @users = User.all
    @posts = Post.where(status: "Published").all
    @replies = Reply.all
    @chatterbox = User.order(replies_count: :desc).limit(10)
    @top10_posts = Post.order(replies_count: :desc).limit(10) 
  end

  def collect
    @post = Post.find(params[:id])
    @post.collects.create!(user: current_user)
    # redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def uncollect
    @post = Post.find(params[:id])
    collects = Collect.where(post: @post, user: current_user)
    collects.destroy_all
    #redirect_back(fallback_location: root_path)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image, :categoty_id, :status, :authorized)
  end

  def published?
    params[:commit] == "Create Post" || params[:commit] == "Update Post"   
  end

  def draft?
    params[:commit] == "Save as Draft"
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/collect.js.erb
<% html = j( render :partial => "shared/collect_btn", :locals => { :@post => @post } ) %>
var collect_btn_div = $("#collect-btn");
$(collect_btn_div).html("<%= html %>");

app/views/posts/edit.html.erb
<%= render partial: "shared/form_post" %>

app/views/posts/feeds.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="col-xs-4">
        <h3>User</h3>
        <div class="form-control">
          <%= @users.count %>
        </div>
      </div>

      <div class="col-xs-4">
        <h3>Post</h3>
        <div class="form-control">
          <%= @posts.count %>
        </div>
      </div>

      <div class="col-xs-4">
        <h3>Comment</h3>
        <div class="form-control">
          <%= @replies.count %>
        </div>
      </div>

<div class="clearfix"></div>
      <div class="col-xs-6">
        <% i=1 %>
        <table class="table">
          <thead>
            <h3>ChatterBox</h3>
          </thead>
          <tbody>
            <% @chatterbox.each do |user| %>
              <tr>
                <th scope="row"><%= i %></th>
                <td><%= link_to user.name, user_path(user) %> </td>
                <td><%= user.replies_count %></td>
              </tr>
              <% i+=1 %>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-xs-6">
        <% j=1 %>
        <table class="table">
          <thead>
            <h3>Most Populer Post</h3>
          </thead>
          <tbody>
            <% @top10_posts.each do |post| %>
              <tr>
                <th scope="row" class="col-xs-1"><%= j %></th>
                <td class="col-xs-7"><%= link_to post.title, post_path(post) %></td>
                <td class="col-xs-4"><%= (post.created_at).strftime("%Y-%m-%d") %></td>
              </tr>
              <% j+=1 %>
            <% end %>
          </tbody>
        </table>
      </div>      
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">

  <h1>文章 前台</h1>

  <div class="row">

    <div class="col-md-12">

      <div>
        <%= link_to 'New post', new_post_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Replies count</th>
            <th>Title</th>
            <th>Last replied at</th>
            <th> Viewed count</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <th scope="row"><%= post.replies_count %></th>
            <td><%= link_to post.title, post_path(post) %></td>
            <td>
              <% if post.replies.present? %>
                <%= (post.replies.last.created_at).strftime("%Y-%m-%d") %>
              <% end %>
            </td>
            <td>
              <%= link_to 'Show', post_path(post) %>
              <%= link_to 'Edit', edit_post_path(post) %>
              <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm:"Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @posts %>
      </div>

    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">

    <% if @post.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>
    
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      </div>

      <div class="form-group">
        <%= f.text_area :description, class: "form-control", placeholder: "" %>
      </div>

      <div class="form-group">
        <%= image_tag @post.image, width: '300px' if @post.image? %>
        <%= f.file_field :image, class: "form-control-file" %>
      </div>


      <h4> Who Can See </h4>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
        <label class="form-check-label" for="inlineCheckbox1">1</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
        <label class="form-check-label" for="inlineCheckbox2">2</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
        <label class="form-check-label" for="inlineCheckbox3">3</label>
      </div>

      <h4> Category </h4>  
      <%= f.collection_check_boxes :category_id, Category.all, :id, :name %>
  

      <h4> Status: </h4>

      <div class="form-group">
        <!-- Save draft btn -->
      </div>

      <div class="form-group">
        <%= f.submit "Save as Draft", class: "btn btn-default" %>
        <%= f.submit "Publish", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h2 class="col-xs-8 col-sm-10"><%= @post.title %></h2>
    <div id="collect-btn" class="col-xs-2 col-sm-1">
      <%= render partial: "shared/collect_btn" %>
    </div>
    <div id="comment-btn" class="col-xs-3 col-sm-1">
      <%= link_to 'Comment', post_path(@post, anchor: "comment-form"), class: "btn btn-primary" %>
    </div>

  <!-- Comment btn -->
  <div class="clearfix"></div>
  <div class="col-xs-3">
    <%= link_to user_path(@post.user) do %>
      <div class="col-xs-12">
        <%= image_tag @post.user.avatar, class: "img-responsive img-rounded" %>
      </div>
      <div class="col-xs-6">
        <h4> <%= @post.user.name %> </h4>   
      </div>
    <% end %>
    <div id="post-friend" class="col-xs-6">
      <%= render partial: "shared/friend", locals: {user: @post.user}, class: "pull-right" %>
    </div> 
  </div>
  <div class="col-xs-9">
    <%= image_tag @post.image, style:"width: 90px; height: auto;" %> 
      <p> <%= @post.description %> </p>
      <% if @post.user == current_user %>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-primary"  %>
      <% elsif current_user.admin? %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-primary"  %>            
      <% end %>
  </div>

  <div class="clearfix"></div>
  <h3> Replies: </h3>
  <% @post.replies.each do |reply| %>
    <div class="col-xs-2 col-xs-offset-1">
      <%= link_to user_path(reply.user) do %>
        <div class="col-xs-12">
          <%= image_tag reply.user.avatar, class: "img-responsive img-rounded"  %>
        </div>
        <div class="col-xs-6">
          <h4> <%= reply.user.name %> </h4> 
        </div>
      <% end %>
        <div id="reply-friend" class="col-xs-6">
          <%= render partial: "shared/friend", locals: {user: reply.user} %>
        </div>  
    </div>

    <div class="col-xs-9">
      <p> <%= reply.comment %> </p>
      <% if reply.user == current_user %>
        <%= link_to 'Edit', post_path(@post, reply_id: reply.id, anchor: "comment-form"), class: "btn btn-primary"  %>
        <%= link_to 'Delete', post_reply_path(@post, reply), method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-primary"  %>
      <% elsif current_user.admin? %>
        <%= link_to 'Delete', post_reply_path(@post, reply), method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-primary"  %>
      <% end %>
    </div>
    <div class="clearfix"></div>
    <hr />
  <% end %>

  <div class="text-center">
    <%= paginate @replies %>
  </div>

  <div class="col-xs-6 col-xs-offset-3">
    <div class="form-group comment-group" id="comment-form">  
      <%= form_for [@post, @reply] do |f|%>
        <div class="form-group">
          <%= f.text_area :comment, placeholder: "add comment", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end%>
    </div>
  </div>
</div>

app/views/posts/uncollect.js.erb
<% html = j( render :partial => "shared/collect_btn", :locals => { :@post => @post } ) %>
var collect_btn_div = $("#collect-btn");
$(collect_btn_div).html("<%= html %>");