config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index" 
  resources :posts do
    resources :replies
    collection do
      get :feeds
    end

    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: :show
  resources :users, only: [:show, :edit, :update] do
    member do
      get :my_comment
      get :my_collect
      get :my_draft
      get :my_friend
    end
  end

  resources :friendships, only: [:create, :destroy]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  namespace :admin do
    root "categories#index"
    resources :categories
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- 導覽列 -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <form class="form-inline">
          <%= link_to "PetForum", root_path, class: "navbar-brand" %>
          <%= link_to 'Feeds', feeds_posts_path, class: "navbar-brand" %>
          <%= link_to 'All post', root_path, class: "navbar-brand" %>
          <%= link_to 'New post', new_post_path, class: "navbar-brand" %>
        </form>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#right-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="right-navbar-collapse">
        <ul class="pull-right text-right nav navbar-nav">
          <% if current_user %>
            <li><p class="navbar-text"><%= current_user.email %></p></li>
            
            <% if current_user.admin? %>
              <li><%= link_to '(Admin)', admin_categories_path %></li>
            <% end %>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
          <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>